### ISSUE TITLE
Can't sign in via WebDAV: "There was an error retrieving files!"

### ISSUE THREAD

**Issue by ghost** [200ok-ch/organice#543]
**Describe the bug**
When trying to sign in via Webdav, after putting in the url, username and password of my nextcloud webdav, I get the following error: "There was an error retrieving files!" 

**To Reproduce**
1. 
Launch docker-compose.yml 
```
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

########################### SERVICES
services:
# All services / apps go below this line
  organice:
    image: 'twohundredok/organice:latest'
    ports:
      - '5000:5000'
    networks:
      - t2_proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.organ-rtr.entrypoints: web, websecure
      traefik.http.routers.organ-rtr.rule: Host(`organice.${DOMAINNAME}`)
      traefik.http.routers.organ-rtr.tls: "true"
      traefik.http.routers.organ-rtr.tls.certresolver: le
#      traefik.http.routers.organ-rtr.service: wallabag-svc
      traefik.http.services.organ-rtr.loadbalancer.server.port: "5000" 

```

2. Navigate to organice.example.xyz and sign in 

3. Select WebDAV

4a enter base url of nextcloud instance:
URL: nextcloud.example.xyz
Username: user
Password: password

4b. 
URL: http://nextcloud.example.xyz/remote.php/dav/files/user/
Username: user
Password: password

5. Receive error: 
 "There was an error retrieving files!"

**Expected behavior**
Organice should accept these details.

**Desktop (please complete the following information):**
 - Client: Arch
 - Browser: firefox 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e 
 - OS: Android 10
 - Browser firefox

 context**
 Webdav folders works fine on Dolphin (KDE file browser).
